config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :tasks
  root 'sessions#new' 
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: {in: 1..30}
    validates :email, presence: true, uniqueness: true, length: {maximum: 255},
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation {email.downcase!}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    has_many :tasks, dependent: :destroy
    before_destroy :check_if_is_last_admin, prepend: true
    before_update :check_if_admin, prepend: true

    private
    def check_if_is_last_admin
        throw :abort if User.where(is_admin: true).count == 1
    end

    def check_if_admin
        self.is_admin = true if User.where(is_admin: true).count == 1
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :access_denied

  # GET /users or /users.json
  def index
    @all_users_count = User.count
    @users = User.order(created_at: :desc).page(params[:page]).per(5).includes(:tasks)
  end

  # GET /users/1 or /users/1.json
  def show
    @tasks = @user.tasks.page(params[:page]).per(5)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.is_admin = false

    respond_to do |format|
      if @user.save        
        format.html { redirect_to admin_users_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :is_admin)
    end

    def access_denied
      redirect_to user_path(current_user) if !current_user.is_admin
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.is_admin = false

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        
        format.html { redirect_to user_path(@user.id), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
    def choose_new_or_edit(user)
        if action_name == 'new' || action_name == 'create'
            admin_users_path
        elsif action_name == 'edit'
            admin_user_path(user)
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class:"col-4") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :password, class:"form-label" %>
    <%= form.text_field :password, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped table-bordered text-center">
  <thead>
    <tr>
      <th>Name</th>
      <td><%= current_user.name %></td>
    </tr>
  </thead>

  <tbody>
      <tr>
        <th>Email</th>
        <td><%= current_user.email %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'My Tasks', tasks_path, class:"btn btn-success" %>
<%= link_to 'All Tags', tags_path, class:"btn btn-outline-success" %>