config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :tasks
  root 'sessions#new' 
  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryleafProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if logged_in? %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"btn btn-danger" %>
        <%= link_to "My Page", user_path(current_user.id), class:"btn btn-info" %>
        <%= link_to 'Admin pannel', admin_users_path, class:"btn btn-outline-danger" if current_user.is_admin %>
      <% else %>
      　<%= link_to "Sign up", new_user_path, class:"btn btn-info" %>
        <%= link_to "Login", new_session_path, class:"btn btn-outline-info" %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>